version: '3.4'
services:
  gql:
    build:
      context: ./services/gql
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/gql:/app
    environment:
      - GRAPHQL_SERVICE_PORT=80
      - USER_SERVICE_NAME=user
      - USER_SERVICE_PORT=50051
      - AUTH_SERVICE_NAME=auth
      - AUTH_SERVICE_PORT=50052
    ports:
      - 80:80
    tty: true
  user:
    build:
      context: ./services/user
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/user:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - USER_SERVICE_PORT=50051
    ports:
      - 50051:50051
    tty: true
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/auth:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - AUTH_SERVICE_PORT=50052
    ports:
      - 50052:50052
    tty: true
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
      - DATABASE_HOST=localhost