version: '3.4'
services:
  user:
    build:
      context: ./services/user
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/user:/app
    environment:
      - USER_SERVICE_PORT=50051
    ports:
      - 50051:50051
    tty: true