version: '3.4'
services:
  user:
    build:
      context: ./services/user
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/user:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=password
      - USER_SERVICE_PORT=50051
    ports:
      - 50051:50051
    tty: true
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
      - DATABASE_HOST=localhost