name: CI

on:
  push:
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Auth
        run: |
          services/auth && make test
      - name: Test pwd
        run: |
          pwd
