name: CI

on:
  push:
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Auth
        working-directory: ./services/auth
        run: make test
      - name: Test pwd
        run: pwd
