name: CI

on:
  push:
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test auth service
        working-directory: ./services/auth
        run: make test
      - name: test user service
        working-directory: ./services/user
        run: make test
